<script setup lang="ts">
// @ts-ignore - gooey types use unresolved path aliases
import { Heading, Input, Card, CardContent } from '@codinglabsau/gooey'
import { FormBuilder, useSchema } from '../../src/index'

const simpleSchema = useSchema({
  firstname: Input,
  surname: Input,
  secret: {
    component: Input,
    value: 'security by obscurity',
    props: {
      type: 'hidden',
    },
    showLabel: false,
  },
})

const simpleSchemaWithCustomId = useSchema({
  firstname: {
    component: Input,
    label: 'Firstname with custom ID',
    props: {
      id: 'custom_firstname',
    },
  },
})

const submit = () => alert('submitted')
</script>

<template>
  <div class="space-y-12 py-8">
    <section>
      <Heading>The Basics</Heading>

      <p class="mt-2 text-muted-foreground">
        Simple form with text inputs. The schema automatically generates form fields.
      </p>

      <div class="mt-6 grid gap-6 lg:grid-cols-2">
        <Card>
          <CardContent class="pt-6">
            <form @submit.prevent="submit">
              <FormBuilder :schema="simpleSchema" />
            </form>
          </CardContent>
        </Card>

        <pre class="overflow-auto rounded-lg border bg-muted p-4 text-sm">{{
          simpleSchema.form.data()
        }}</pre>
      </div>
    </section>

    <section>
      <Heading as="h2" class="text-xl">Custom ID</Heading>

      <p class="mt-2 text-muted-foreground">
        By default, IDs are auto-generated. You can override with a custom ID via props.
      </p>

      <div class="mt-6 grid gap-6 lg:grid-cols-2">
        <Card>
          <CardContent class="pt-6">
            <form @submit.prevent="submit">
              <FormBuilder :schema="simpleSchemaWithCustomId" />
            </form>
          </CardContent>
        </Card>

        <pre class="overflow-auto rounded-lg border bg-muted p-4 text-sm">{{
          simpleSchemaWithCustomId.form.data()
        }}</pre>
      </div>
    </section>

    <section>
      <Heading as="h2" class="text-xl">Labels</Heading>

      <p class="mt-2 text-muted-foreground">
        Labels are automatically generated by humanising the element name. For example,
        <code class="rounded bg-muted px-1">default_category_id</code> displays as
        <code class="rounded bg-muted px-1">Default Category</code>.
      </p>

      <p class="mt-2 text-muted-foreground">
        Override with <code class="rounded bg-muted px-1">label</code> prop, or hide with
        <code class="rounded bg-muted px-1">showLabel: false</code>.
      </p>
    </section>

    <section>
      <Heading as="h2" class="text-xl">Props</Heading>

      <p class="mt-2 text-muted-foreground">
        Any props in the <code class="rounded bg-muted px-1">props</code> section are forwarded to
        the form element.
      </p>

      <pre class="mt-4 overflow-auto rounded-lg border bg-muted p-4 text-sm"><code>const schema = useSchema({
  firstname: {
    component: Input,
    props: {
      id: 'custom-id',
      placeholder: 'Enter name...',
    },
  },
})</code></pre>
    </section>

    <section>
      <Heading as="h2" class="text-xl">Reactivity</Heading>

      <p class="mt-2 text-muted-foreground">
        To make the schema reactive to prop changes, pass it as a function:
      </p>

      <pre class="mt-4 overflow-auto rounded-lg border bg-muted p-4 text-sm"><code>const schema = useSchema(() => ({
  firstname: Input,
}))</code></pre>
    </section>
  </div>
</template>
